# Generated by Django 6.0.5 on 2026-05-30 03:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=100)),
                ('harga_per_kg', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(db_index=True, max_length=15, unique=True)),
                ('tanggal_terdaftar', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('pegawai', 'Pegawai')], default='pegawai', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_resi', models.CharField(db_index=True, max_length=20, unique=True)),
                ('berat', models.FloatField(help_text='Berat pakaian dalam satuan Kilogram (Kg)')),
                ('total_harga', models.IntegerField()),
                ('status_proses', models.CharField(choices=[('masuk', 'Masuk'), ('dicuci', 'Dicuci'), ('disetrika', 'Disetrika'), ('selesai', 'Selesai (Siap Diambil)'), ('diambil', 'Sudah Diambil')], default='masuk', max_length=15)),
                ('status_pembayaran', models.CharField(choices=[('lunas', 'Lunas'), ('belum_lunas', 'Belum Lunas')], default='belum_lunas', max_length=15)),
                ('metode_pembayaran', models.CharField(choices=[('tunai', 'Tunai'), ('transfer', 'Transfer Bank'), ('qris', 'QRIS')], default='tunai', max_length=10)),
                ('wa_notif_masuk_sent', models.BooleanField(default=False)),
                ('wa_notif_selesai_sent', models.BooleanField(default=False)),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diambil', models.DateTimeField(blank=True, null=True)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pesanan', to='tracking.layanan')),
                ('pegawai_penerima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesanan_masuk', to=settings.AUTH_USER_MODEL)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan', to='tracking.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(help_text='Contoh: Mengubah status menjadi Dicuci', max_length=255)),
                ('waktu_eksekusi', models.DateTimeField(auto_now_add=True)),
                ('pegawai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktivitas', to=settings.AUTH_USER_MODEL)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracking.pesanan')),
            ],
        ),
    ]
