# Generated by Django 6.0.5 on 2026-06-01 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='no_resi',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='RiwayatPekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(help_text='Contoh: Mengubah status menjadi Dicuci', max_length=255)),
                ('waktu_eksekusi', models.DateTimeField(auto_now_add=True)),
                ('pegawai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aktivitas', to=settings.AUTH_USER_MODEL)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='tracking.pesanan')),
            ],
        ),
        migrations.DeleteModel(
            name='LogAktivitas',
        ),
    ]
