# Generated by Django 6.0.5 on 2026-06-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_pesanan_no_resi_riwayatpekerjaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatpekerjaan',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('pegawai', 'Pegawai')], default='pegawai', max_length=10),
        ),
    ]
