# Generated by Django 6.0.5 on 2026-06-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_riwayatpekerjaan_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riwayatpekerjaan',
            name='role',
        ),
    ]
