export default function LoadingBG() {
    return (
        <svg
            width="32"
            height="32"
            viewBox="0 0 8.4666668 8.4666668"
            version="1.1"
            id="svg1"
            sodipodi:docname="loading-bg.svg"
            inkscape:version="1.4.3 (0d15f75042, 2025-12-25)"
            xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
            xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
            xmlns="http://www.w3.org/2000/svg"
            xmlns:svg="http://www.w3.org/2000/svg"
        >
            <sodipodi:namedview
                id="namedview1"
                pagecolor="#ffffff"
                bordercolor="#000000"
                borderopacity="0.25"
                inkscape:showpageshadow="2"
                inkscape:pageopacity="0.0"
                inkscape:pagecheckerboard="0"
                inkscape:deskcolor="#d1d1d1"
                inkscape:document-units="mm"
                inkscape:zoom="15.667956"
                inkscape:cx="21.062096"
                inkscape:cy="13.818011"
                inkscape:window-width="1920"
                inkscape:window-height="1024"
                inkscape:window-x="0"
                inkscape:window-y="0"
                inkscape:window-maximized="1"
                inkscape:current-layer="layer1"
            />
            <defs id="defs1" />
            <g inkscape:label="Layer 1" inkscape:groupmode="layer" id="layer1">
                <ellipse
                    style="opacity:1;fill:#9a0000;fill-opacity:1;stroke:none;stroke-width:0.1;stroke-dasharray:none"
                    id="ellipse10"
                    cx="1.7170311"
                    cy="-4.2333336"
                    rx="0.60792869"
                    ry="1.5525435"
                    transform="rotate(90)"
                />
                <ellipse
                    style="opacity:1;fill:#44aa00;fill-opacity:1;stroke:none;stroke-width:0.1;stroke-dasharray:none"
                    id="ellipse11"
                    cx="6.7496357"
                    cy="-4.2333336"
                    rx="0.60792869"
                    ry="1.5525435"
                    transform="rotate(90)"
                />
                <ellipse
                    style="opacity:1;fill:#c8ab37;fill-opacity:1;stroke:none;stroke-width:0.1;stroke-dasharray:none"
                    id="ellipse12"
                    cx="6.7496357"
                    cy="4.2333331"
                    rx="0.60792869"
                    ry="1.5525435"
                />
                <ellipse
                    style="opacity:1;fill:#0044aa;fill-opacity:1;stroke:none;stroke-width:0.1;stroke-dasharray:none"
                    id="ellipse13"
                    cx="1.7170311"
                    cy="4.2333331"
                    rx="0.60792869"
                    ry="1.5525435"
                />
            </g>
        </svg>
    );
}
